AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - '.ebextenstions/**/*'
    - '.git/**/*'
    - 'bin/**/*'
    - 'certs/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
